pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description: 'Deploy to Cloud?',name: 'isOnCloud')
    }

    stages{
        stage('Demo'){
            steps{
                echo "booleanParam is set to: ${params.isOnCloud}"
            }
        }
    }
}
